name: Generate Snake

on:
  schedule:
    - cron: "0 20 * * *"  # Runs at 20:00 UTC daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: .github/workflows/snake.svg
          github_user_name: Nishant01k  # Make sure this matches your username


      - name: Upload Snake
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: .github/workflows/snake.svg
